# ESPHome LVGL Chart Widget Examples
# =============================================================================
# LVGL v9.4 Chart Widget - Complete Examples
#
# Chart Types: LINE, BAR, SCATTER, NONE
# Update Modes: SHIFT (sliding window), CIRCULAR (ECG-style)
# Axes: PRIMARY_Y, SECONDARY_Y, PRIMARY_X, SECONDARY_X
#
# Actions:
#   - lvgl.chart.set_next_value: Add point (uses SHIFT/CIRCULAR mode)
#   - lvgl.chart.set_value_by_id: Set specific point by index
#   - lvgl.chart.set_value_by_id2: Set X/Y for scatter charts
#   - lvgl.chart.set_series_color: Change series color dynamically
#   - lvgl.chart.set_cursor_point: Move cursor to a point
#   - lvgl.chart.refresh: Refresh chart display
# =============================================================================

# =============================================================================
# EXAMPLE 1: Simple Weather Chart with Home Assistant
# =============================================================================

sensor:
  - platform: homeassistant
    id: weather_temp
    entity_id: weather.forecast_maison
    attribute: temperature
    on_value:
      then:
        # IMPORTANT: Label ID must match the label defined in widgets!
        - lvgl.label.update:
            id: temp_label
            text:
              format: "%.1f°C"
              args: [id(weather_temp).state]
        - lvgl.chart.set_next_value:
            id: weather_chart
            series_id: temp_series
            value: !lambda 'return (int)id(weather_temp).state;'

  - platform: homeassistant
    id: weather_humidity
    entity_id: weather.forecast_maison
    attribute: humidity
    on_value:
      then:
        - lvgl.label.update:
            id: humidity_label
            text:
              format: "%.0f%%"
              args: [id(weather_humidity).state]
        - lvgl.chart.set_next_value:
            id: weather_chart
            series_id: humidity_series
            value: !lambda 'return (int)id(weather_humidity).state;'

lvgl:
  displays:
    - display_id: my_display
      pages:
        # =====================================================================
        # PAGE 1: Weather Chart (LINE) with Labels
        # =====================================================================
        - id: weather_page
          bg_color: 0x000000
          widgets:
            - label:
                id: temp_label
                x: 20
                y: 10
                width: 100
                text: "--.-°C"
                text_color: 0xFF0000

            - label:
                id: humidity_label
                x: 130
                y: 10
                width: 100
                text: "--%"
                text_color: 0x0000FF

            - chart:
                id: weather_chart
                x: 20
                y: 50
                width: 400
                height: 180
                type: LINE
                point_count: 24
                update_mode: SHIFT
                bg_color: 0x1a1a2e
                border_width: 1
                border_color: 0x333333
                div_line_count_hor: 4
                div_line_count_ver: 6
                items:
                  line_width: 2
                indicator:
                  radius: 3
                axis_primary_y:
                  min_value: -10
                  max_value: 40
                axis_secondary_y:
                  min_value: 0
                  max_value: 100
                series:
                  - id: temp_series
                    color: 0xFF0000
                    axis: PRIMARY_Y
                  - id: humidity_series
                    color: 0x0000FF
                    axis: SECONDARY_Y

        # =====================================================================
        # PAGE 2: Chart with Axis Ticks and Labels
        # =====================================================================
        - id: ticks_page
          bg_color: 0x1a1a2e
          widgets:
            - label:
                x: 20
                y: 10
                text: "Chart with Axis Ticks"
                text_color: 0xFFFFFF

            - chart:
                id: ticks_chart
                x: 60
                y: 50
                width: 350
                height: 200
                type: LINE
                point_count: 12
                bg_color: 0x0a0a14
                border_width: 1
                border_color: 0x333333
                div_line_count_hor: 5
                div_line_count_ver: 6
                items:
                  line_width: 2
                indicator:
                  radius: 4
                # Axis with ticks and labels
                axis_primary_y:
                  min_value: 0
                  max_value: 100
                  major_tick_length: 10     # Length of major ticks in pixels
                  minor_tick_length: 5      # Length of minor ticks
                  major_tick_count: 6       # Number of major ticks (0, 20, 40, 60, 80, 100)
                  minor_tick_count: 4       # Minor ticks between each major tick
                  label_enabled: true       # Show numeric labels
                  draw_size: 50             # Space for labels
                axis_primary_x:
                  min_value: 0
                  max_value: 12
                  major_tick_length: 8
                  minor_tick_length: 4
                  major_tick_count: 7
                  minor_tick_count: 1
                  label_enabled: true
                  draw_size: 30
                series:
                  - id: ticks_series
                    color: 0x00FF00
                    points: [10, 25, 45, 30, 55, 70, 60, 85, 75, 90, 80, 95]

        # =====================================================================
        # PAGE 3: Chart with Cursor (click to show cursor)
        # =====================================================================
        - id: cursor_page
          bg_color: 0x1a1a2e
          widgets:
            - label:
                x: 20
                y: 10
                text: "Click chart to show cursor"
                text_color: 0xFFFFFF

            - label:
                id: cursor_value_label
                x: 20
                y: 35
                text: "Point: --"
                text_color: 0xFFCC00

            - chart:
                id: cursor_chart
                x: 20
                y: 70
                width: 400
                height: 200
                type: LINE
                point_count: 12
                clickable: true              # Enable click detection
                bg_color: 0x0a0a14
                border_width: 1
                border_color: 0x333333
                div_line_count_hor: 5
                div_line_count_ver: 12
                items:
                  line_width: 2
                indicator:
                  radius: 4
                axis_primary_y:
                  min_value: 0
                  max_value: 100
                series:
                  - id: cursor_series
                    color: 0x2196F3
                    points: [20, 35, 50, 45, 60, 75, 65, 80, 70, 85, 90, 95]
                # Add a cursor to the chart
                cursors:
                  - id: my_cursor
                    color: 0xFF0000          # Red cursor line
                    direction: ALL           # Show both horizontal and vertical lines
                # When a point is clicked, move cursor to that point
                on_value:
                  then:
                    - lvgl.chart.set_cursor_point:
                        id: cursor_chart
                        cursor_id: my_cursor
                        series_id: cursor_series
                        point_index: !lambda 'return point_index;'
                    - lvgl.label.update:
                        id: cursor_value_label
                        text:
                          format: "Point: %d"
                          args: [point_index]

        # =====================================================================
        # PAGE 4: Scatter Chart (Static)
        # =====================================================================
        - id: scatter_page
          bg_color: 0x1a1a2e
          widgets:
            - label:
                x: 20
                y: 10
                text: "Scatter Chart"
                text_color: 0xFFFFFF

            - chart:
                id: scatter_chart
                x: 50
                y: 50
                width: 250
                height: 250
                type: SCATTER
                point_count: 10
                bg_color: 0x0a0a14
                border_width: 1
                border_color: 0x333333
                div_line_count_hor: 5
                div_line_count_ver: 5
                items:
                  line_width: 0
                indicator:
                  bg_color: 0xFF6600
                  radius: 6
                axis_primary_y:
                  min_value: 0
                  max_value: 100
                axis_primary_x:
                  min_value: 0
                  max_value: 100
                series:
                  - id: scatter_series
                    color: 0xFF6600
                    x_points: [10, 20, 30, 40, 50, 60, 70, 80, 90, 95]
                    y_points: [15, 35, 25, 55, 45, 75, 65, 85, 70, 90]

        # =====================================================================
        # PAGE 5: Bar Chart
        # =====================================================================
        - id: bar_page
          bg_color: 0x1a1a2e
          widgets:
            - label:
                x: 20
                y: 10
                text: "Monthly Sales (BAR)"
                text_color: 0xFFFFFF

            - chart:
                id: bar_chart
                x: 20
                y: 50
                width: 400
                height: 200
                type: BAR
                point_count: 12
                bg_color: 0x0a0a14
                border_width: 1
                border_color: 0x333333
                div_line_count_hor: 5
                div_line_count_ver: 12
                items:
                  bg_opa: 80%
                axis_primary_y:
                  min_value: 0
                  max_value: 500
                series:
                  - id: bar_series
                    color: 0x4CAF50
                    points: [120, 180, 240, 200, 280, 350, 420, 380, 320, 290, 250, 200]

# =============================================================================
# TROUBLESHOOTING
# =============================================================================
#
# Labels show "--" or placeholder text:
#   - Check that entity_id exists in Home Assistant
#   - Check that attribute name is correct (temperature, humidity, etc.)
#   - Make sure label ID in on_value matches label ID in widgets
#   - Check ESPHome logs for sensor values
#
# Axis ticks not showing:
#   - Set major_tick_length > 0 to enable ticks
#   - Set draw_size large enough for labels (50+ recommended)
#   - Make sure min_value and max_value are set
#
# Cursor not showing:
#   - Make sure clickable: true is set on the chart
#   - Define cursors section with at least one cursor
#   - Use lvgl.chart.set_cursor_point action to position cursor
#
# Chart doesn't update:
#   - Make sure series_id matches the series defined in the chart
#   - Check that the chart ID is correct
#   - Verify sensor is receiving data (check logs)
