[Rainmeter]
AccurateText=1
Update=#SPEED#
@Includelink="LINK.inc"

[MeasureMyColor]
Measure=Script
ScriptFile=ColorRotate.lua
; MySaturation and MyBrightness can be 0.0 (none) to 1.0 (full)
MySaturation=0.8
MyBrightness=1.0


[ImageNumberCalc]
Measure=Calc
Formula=(ImageNumberCalc % #NUMFRAMES#) + 1

[ImageMeter]
Meter=Image
H=#ALTEZZA#
ImageName=#NOMEGIF#\#NOMEGIF#-[ImageNumberCalc].png
ImageTint=[MeasureMyColor]
DynamicVariables=1
Antialias=1